# 项目相关配置
sinosoft:
  # 名称
  name: ETP
  # 版本
  version: 0.1.3
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/sinosoft/uploadPath，Linux配置 /home/sinosoft/uploadPath）
  profile: /home/projects/etp/etp_server/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  # 若为 true 为本地调试模式
  localDev: true
  parsrFileServer: http://localhost:9999

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  5000MB
       # 设置总上传的文件大小
       max-request-size:  5000MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 10.153.3.13
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 11
    # 密码
    password: Zkr@123
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认 7 天） 60（分钟） x 24（小时） x 7（天）
    expireTime: 10080

## MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.sinosoft.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# MyBatis Plus配置
#mybatis-plus:
#  # 不支持多包, 如有需要可在注解配置 或 提升扫包等级
#  # 例如 com.**.**.mapper
#  mapperPackage: com.sinosoft.**.mapper
#  # 对应的 XML 文件位置
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.sinosoft.**.domain
#  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
#  checkConfigLocation: false
#  configuration:
#    # 自动驼峰命名规则（camel case）映射
#    mapUnderscoreToCamelCase: false
#    # MyBatis 自动映射策略
#    # NONE：不启用 PARTIAL：只对非嵌套 resultMap 自动映射 FULL：对所有 resultMap 自动映射
#    autoMappingBehavior: PARTIAL
#    # MyBatis 自动映射时未知列或未知属性处理策
#    # NONE：不做处理 WARNING：打印相关警告 FAILING：抛出异常和详细信息
#    autoMappingUnknownColumnBehavior: NONE
#    # 更详细的日志输出 会有性能损耗 org.apache.ibatis.logging.stdout.StdOutImpl
#    # 关闭日志记录 (可单纯使用 p6spy 分析) org.apache.ibatis.logging.nologging.NoLoggingImpl
#    # 默认日志输出 org.apache.ibatis.logging.slf4j.Slf4jImpl
#    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    # 是否打印 Logo banner
#    banner: false
#    dbConfig:
#      # 主键类型
#      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
#      idType: ASSIGN_ID
#      # 逻辑已删除值
#      logicDeleteValue: 2
#      # 逻辑未删除值
#      logicNotDeleteValue: 0
#      # 字段验证策略之 insert,在 insert 的时候的字段验证策略
#      # IGNORED 忽略 NOT_NULL 非NULL NOT_EMPTY 非空 DEFAULT 默认 NEVER 不加入 SQL
#      insertStrategy: NOT_NULL
#      # 字段验证策略之 update,在 update 的时候的字段验证策略
#      updateStrategy: NOT_NULL
#      # 字段验证策略之 select,在 select 的时候的字段验证策略既 wrapper 根据内部 entity 生成的 where 条件
#      where-strategy: NOT_NULL


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 替换 URL 前缀
storage:
  # 替换 URL 前缀开关
  enabled: true
  # 匹配字段名
  fields: url,fm,fmt,dt,kjdz,hdfm,tempFile,download,analysis,content,noticeContent,cover

