basic:
  # profile: D:/ruoyi/uploadPath
  profile: /home/projects/etp/etp_server/uploadPath

spring:
  datasource:
    # url: jdbc:mysql://10.153.3.13:3306/etp_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    # url: jdbc:mysql://10.153.3.13:3306/etp_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    url: jdbc:mysql://192.168.1.187:3306/etp_uat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: pajy@303
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.1.187
    port: 6379
#    password: Zkr@123
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.sinosoft.entity
  configuration:
    map-underscore-to-camel-case: true

